# Generated by Django 5.0.6 on 2025-11-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_author_remove_post_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='Пост пока пустой'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Без заголовка', max_length=200),
        ),
    ]
